// The website and Sparkle share one source of release information.
// Keep the newest stable release first, as generated by Sparkle's generate_appcast.
(async () => {
  const button = document.getElementById("download-button");
  const status = document.getElementById("download-status");
  const details = document.getElementById("release-details");
  const sparkle = "http://www.andymatuschak.org/xml-namespaces/sparkle";
  try {
    const feedURL = new URL("appcast.xml", window.location.href);
    const response = await fetch(feedURL, { cache: "no-cache", signal: AbortSignal.timeout(10000) });
    if (!response.ok) throw new Error("Update feed unavailable");
    const xml = new DOMParser().parseFromString(await response.text(), "application/xml");
    if (xml.querySelector("parsererror") || !xml.querySelector("rss > channel")) throw new Error("Invalid update feed");
    const release = [...xml.querySelectorAll("channel > item")].find(item =>
      !item.getElementsByTagNameNS(sparkle, "channel").length &&
      [...item.children].some(el => el.localName === "enclosure" && el.hasAttribute("url"))
    );
    if (!release) return; // No package has been published yet.
    const enclosure = [...release.children].find(el => el.localName === "enclosure");
    const downloadURL = new URL(enclosure.getAttribute("url"), feedURL);
    if (downloadURL.protocol !== "https:") throw new Error("Download must use HTTPS");
    const value = name => release.getElementsByTagNameNS(sparkle, name)[0]?.textContent.trim()
      || enclosure.getAttributeNS(sparkle, name);
    const version = value("shortVersionString") || value("version");
    if (!version) throw new Error("Missing release version");
    const minimumOS = value("minimumSystemVersion");
    const bytes = Number(enclosure.getAttribute("length"));
    const format = /\.dmg$/i.test(downloadURL.pathname) ? "DMG" : "Mac";
    button.href = downloadURL.href;
    button.removeAttribute("aria-disabled");
    button.textContent = `Download for Mac`;
    status.textContent = `InputsCounter ${version}`;
    details.textContent = [format, minimumOS && `macOS ${minimumOS} or later`, Number.isFinite(bytes) && bytes > 0 && `${(bytes / 1048576).toFixed(1)} MB`].filter(Boolean).join(" · ");
    details.hidden = false;
  } catch (error) {
    status.textContent = "Download information is temporarily unavailable. Please try again later.";
    button.textContent = "Download unavailable";
  }
})();
